import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  users: defineTable({
    name: v.optional(v.string()),
    email: v.string(),
    imageUrl: v.optional(v.string()),
    clerkUserId: v.string(),
    role: v.union(
      v.literal("user"),
      v.literal("admin")
    ),
  }).index("byClerkUserId", ["clerkUserId"]),
  homePageContent: defineTable({
    headingPart1: v.string(),
    headingHighlight: v.string(),
    headingPart2: v.string(),
    headingPart3: v.string(),
    subtitle: v.string(),
    projectsCount: v.string(),
    yearsExperience: v.string(),
    satisfaction: v.string(),
    support: v.string(),
    role: v.string(),
    roleDescription: v.string(),
    backendSkills: v.string(),
    frontendSkills: v.string(),
    heroImage: v.union(v.id("_storage"), v.null()),
    cvFile: v.union(v.id("_storage"), v.null())
  }),
  aboutSection: defineTable({
    profileImage: v.union(v.id("_storage"), v.null()),
    heading: v.string(),
    description1: v.string(),
    description2: v.string(),
    experience: v.number(),
    projects: v.number(),
    available: v.string(),
  }),
  services: defineTable({
    title: v.string(),
    icon: v.string(),
    description: v.string(),
    features: v.array(v.string()),
  }),
  skills: defineTable({
    name: v.string(),
    years: v.number(),
    image: v.string(),
    category: v.string(),
  }),
  projects: defineTable({
    title: v.string(),
    shortDescription: v.string(),
    longDescription: v.string(),
    techIcons: v.array(v.string()),
    images: v.array(v.id('_storage')),
    githubLink: v.string(),
    liveLink: v.string(),
  }),
  workExperience: defineTable({
    company: v.string(),
    position: v.string(),
    startDate: v.string(),
    endDate: v.union(v.string(), v.null()),
    shortDescription: v.string(),
    longDescription: v.string(),
    achievements: v.array(v.string()),
    technologies: v.array(v.string()),
    companyLink: v.union(v.string(), v.null()),
  }),
  education: defineTable({
    institution: v.string(),
    degree: v.string(),
    field: v.string(),
    startDate: v.string(),
    endDate: v.union(v.string(), v.null()),
    gpa: v.union(v.string(), v.null()),
    description: v.union(v.string(), v.null()),
    achievements: v.array(v.string()),
    courses: v.array(v.string()),
    logo: v.union(v.string(), v.null()),
  }),
  certificates: defineTable({
    title: v.string(),
    issuer: v.string(),
    issueDate: v.string(),
    expiryDate: v.union(v.string(), v.null()),
    credentialLink: v.union(v.string(), v.null()),
    description: v.union(v.string(), v.null()),
    skills: v.array(v.string()),
    image: v.union(v.string(), v.null()),
  }),
  chats: defineTable({
    from: v.string(),
    to: v.string(),
    message: v.string(),
    timestamp: v.number(),
    fromName: v.string(),
    fromImage: v.optional(v.string()),
  }),
});